# **Data Encoding**

In data science, machine learning models are essentially massive calculators. They run on linear algebra and multivariable calculus, which means they can only read and process numbers.

If your dataset contains categorical data—such as text strings like "Low", "Medium", "High", or countries like "USA", "India", "Germany"—a model cannot natively interpret it. Data Encoding is the feature engineering process of translating these text categories into clean, numerical values without losing their core structural meaning.

Label Encoding is a categorical encoding technique that converts text categories into numerical labels. Each unique category is assigned a unique integer value.

Most Machine Learning algorithms work with mathematical operations such as:

*   Addition
*   Subtraction
*   Distance Calculation
*   Matrix Multiplication
*   Gradient Descent

They cannot directly understand text values like:
*   Male
*   Female

*   Red
*   Blue
*   Green

Therefore, we convert these categorical values into numbers using encoding techniques.

# **Types of Data Encoding**

**1. Label Encoding**

Label Encoding is a categorical encoding technique that converts text categories into numerical labels. Each unique category is assigned a unique integer value.

Machine Learning algorithms work with numerical data, not text. Therefore, when a dataset contains categorical values such as:

**Gender**


---
* Male
* Female
* Male

we must convert them into numbers before training a model.


Label Encoding is one of the simplest encoding techniques and is commonly used when categories have a natural order or when the target variable contains categorical values


Example:

| Gender |
| ------ |
| Male   |
| Female |

After Encoding:

| Gender |
| ------ |
| 1      |
| 0      |

Here:

```text
Female → 0
Male   → 1
```

---

**Why Label Encoding is Required**

Machine Learning algorithms cannot understand:

```text
Male
Female
```

But they can understand:

```text
0
1
```

Encoding converts human-readable categories into machine-readable numbers.

---

**How Label Encoding Works**

Suppose we have:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |

Label Encoder automatically assigns numbers.

Result:

| Color |
| ----- |
| 2     |
| 0     |
| 1     |

Mapping:

```text
Blue  → 0
Green → 1
Red   → 2
```

Notice that LabelEncoder usually assigns numbers alphabetically.

---

###Internal Working

**Step 1**

Find unique categories.

```text
Blue
Green
Red
```

---

**Step 2**

Sort categories alphabetically.

```text
Blue
Green
Red
```

---

**Step 3**

Assign integer values.

```text
Blue  → 0
Green → 1
Red   → 2
```

---

**Step 4**

Replace original values.

Original:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |

Encoded:

| Color |
| ----- |
| 2     |
| 0     |
| 1     |

---

**Understanding the Biggest Problem**

This is one of the most important interview concepts.

Suppose:

| City   |
| ------ |
| Delhi  |
| Mumbai |
| Pune   |

After Label Encoding:

| City |
| ---- |
| 0    |
| 1    |
| 2    |

The model may think:

```text
Pune > Mumbai > Delhi
```

or

```text
2 > 1 > 0
```

This creates a false relationship.

In reality:

```text
Delhi
Mumbai
Pune
```

have no order.

---

**Real-Life Example of the Problem**

Imagine:

```text
Apple = 0
Banana = 1
Orange = 2
```

A model might interpret:

```text
Orange > Banana > Apple
```

which is meaningless.

This is why Label Encoding should not be used for most nominal features.

---

### When to Use Label Encoding

**1. Target Variable (y)**

This is the most common use case.

Example:

Loan Approval Prediction

Target:

```text
Approved
Rejected
```

Encode:

```text
Approved = 1
Rejected = 0
```

Perfectly acceptable.

---

**2. Binary Categories**

Example:

```text
Yes / No
True / False
Male / Female
Pass / Fail
```

Example:

```text
Yes = 1
No  = 0
```

No issue.

---

**3. Some Tree-Based Algorithms**

Examples:

* Decision Tree
* Random Forest
* XGBoost
* LightGBM

These models are less affected by numeric ordering because they split data based on conditions.

However, One-Hot Encoding is often still preferred for nominal data.

---

## When NOT to Use Label Encoding

**Nominal Data**

Examples:

```text
City
Country
Color
Department
Product Category
```

No order exists.

Avoid Label Encoding.

---

### Wrong Example

| City   |
| ------ |
| Delhi  |
| Mumbai |
| Pune   |

Encoding:

```text
Delhi = 0
Mumbai = 1
Pune = 2
```

Creates artificial ranking.

---

### Better Solution

Use One-Hot Encoding.

| Delhi | Mumbai | Pune |
| ----- | ------ | ---- |
| 1     | 0      | 0    |
| 0     | 1      | 0    |
| 0     | 0      | 1    |

---

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = ['red' , 'green' , 'blue' , 'green']

In [ ]:
# Creating Object of LabelEncoder() class
label_encoder = LabelEncoder()

In [ ]:
label_encoder

LabelEncoder()

In [ ]:
label_encoder.fit_transform(data)

array([2, 1, 0, 1])

In [ ]:
encoded_data = label_encoder.fit_transform(data)

In [ ]:
print("Original_data",data)
print("Encoded_data",encoded_data)

Original_data ['red', 'green', 'blue', 'green']
Encoded_data [2 1 0 1]

In [ ]:
encoded_data

array([2, 1, 0, 1])

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    'Gender':['Male','Female','Male','Female']
})

le = LabelEncoder()

df['Gender'] = le.fit_transform(df['Gender'])

print(df)

   Gender
0       1
1       0
2       1
3       0

**2. Ordinal Encoding**

**Ordinal Encoding** is a categorical encoding technique used for **ordinal data**, where categories have a meaningful order or ranking. It converts each category into a numerical value while preserving the natural order between categories.

Unlike nominal data, ordinal data contains information about relative ranking.

For example:

```text
Small < Medium < Large
```

or

```text
High School < Bachelor < Master < PhD
```

In such cases, assigning numbers helps Machine Learning models understand the order present in the data.

---

**Why Ordinal Encoding is Needed**

Consider the feature:

| Education   |
| ----------- |
| High School |
| Bachelor    |
| Master      |
| PhD         |

Machine Learning algorithms cannot understand text values directly.

Using Ordinal Encoding:

| Education |
| --------- |
| 1         |
| 2         |
| 3         |
| 4         |

Now the model can understand that:

```text
PhD > Master > Bachelor > High School
```

which matches the real-world relationship.

---


**What is Ordinal Data?**

Ordinal data consists of categories that have a meaningful order.

**Examples**

**Education Level**

```text
High School
Bachelor
Master
PhD
```

**Customer Satisfaction**

```text
Poor
Average
Good
Excellent
```

**Shirt Size**

```text
Small
Medium
Large
XL
```
**Credit Rating**

```text
Low
Medium
High
Very High
```

---

**How Ordinal Encoding Works**

**Original Data**

| Experience Level |
| ---------------- |
| Beginner         |
| Intermediate     |
| Expert           |

---

**Define Order**

```text
Beginner     = 1
Intermediate = 2
Expert       = 3
```

---

**Encoded Data**

| Experience Level |
| ---------------- |
| 1                |
| 2                |
| 3                |

The model now understands progression.

---

**Why Ordinal Encoding Works**

Because the assigned numbers represent a real-world ranking.

Example:

```text
Poor = 1
Average = 2
Good = 3
Excellent = 4
```

The distance between categories reflects increasing levels of quality.

The numerical values carry meaningful information.

---

**7. Advantages of Ordinal Encoding**

* Preserves Order
* Memory Efficient
* Faster Training

**Suitable for Tree Models**

Works well with:
* Decision Tree
* Random Forest
* XGBoost
* LightGBM

---

**Limitations of Ordinal Encoding**

**Assumes Equal Distance**

Example:

```text
Poor = 1
Average = 2
Good = 3
Excellent = 4
```

The model may assume:

```text
Average - Poor
=
Excellent - Good
```

which may not be true.

---

**Not Suitable for Nominal Data**

Example:

```text
Delhi
Mumbai
Pune
```

Encoding:

```text
Delhi = 1
Mumbai = 2
Pune = 3
```

This creates a fake ranking.

No actual order exists.

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

In [ ]:
df = pd.DataFrame({
    'size' : ['small' , 'medium' , 'large' , 'medium' , 'small' , 'large']
})

In [ ]:
df.head()

     size
0   small
1  medium
2   large
3  medium
4   small

In [ ]:
encoder = OrdinalEncoder(categories=[['small' , 'medium' , 'large']])

In [ ]:
encoder

OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [ ]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [ ]:
# Using Scikit-Learn
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

# Create a DataFrame with an 'Education' column
education_data = pd.DataFrame({
    'Education': ['High School', 'Bachelor', 'Master', 'PhD', 'High School', 'Bachelor']
})

encoder = OrdinalEncoder(
    categories=[
        ['High School',
         'Bachelor',
         'Master',
         'PhD']
    ]
)

# Encode the 'Education' column and store it in a new column
education_data['Education_Encoded'] = encoder.fit_transform(
    education_data[['Education']]
)

# Display the combined DataFrame with original and encoded data
print("Original and Encoded Education Data :\n")
display(education_data)

Original and Encoded Education Data :

     Education  Education_Encoded
0  High School                0.0
1     Bachelor                1.0
2       Master                2.0
3          PhD                3.0
4  High School                0.0
5     Bachelor                1.0

In [ ]:
# Using Pandas Mapping
import pandas as pd

# Create a DataFrame with an 'Education' column for demonstration
education_data_pandas = pd.DataFrame({
    'Education': ['High School', 'Bachelor', 'Master', 'PhD', 'High School', 'Bachelor']
})

# Define the ordinal map
education_map = {
    'High School': 1,
    'Bachelor': 2,
    'Master': 3,
    'PhD': 4
}

# Apply the mapping to create a new encoded column
education_data_pandas['Education_Encoded'] = education_data_pandas['Education'].map(education_map)

# Display the original and encoded data for comparison in a single DataFrame
print("Original and Encoded Education Data (using Pandas Mapping):\n")
display(education_data_pandas)

Original and Encoded Education Data (using Pandas Mapping):

     Education  Education_Encoded
0  High School                  1
1     Bachelor                  2
2       Master                  3
3          PhD                  4
4  High School                  1
5     Bachelor                  2

**3. One-Hot Encoding**

One-Hot Encoding (OHE) is a feature engineering technique used to convert categorical (nominal) data into numerical format by creating a separate binary column for each category.


---


Machine Learning algorithms cannot directly understand text values such as:

*   Red
*   Blue
*   Green

One-Hot Encoding converts each category into a new column containing only:



*   0 = Category Not Present
*   1 = Category Present

It is called "One-Hot" because only one column is "hot" (1) for a particular category, while all others remain 0.

One-Hot Encoding is considered one of the safest and most commonly used encoding techniques because it does not introduce any artificial ordering between categories

**Advantages**

*   No false ordering
*   Easy interpretation
*   Works well with many algorithms

**Disadvantages**

High Cardinality Problem.

Example:

`City Column`

Contains:

`500 Cities`

One-Hot Encoding creates:

`500 Columns`

Huge memory usage.

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df =pd.DataFrame({
    'weather' : ['sunny' , 'cloudy' , 'rainy' , 'sunny' , 'cloudy' , 'rainy']
  })

In [ ]:
df.head()

  weather
0   sunny
1  cloudy
2   rainy
3   sunny
4  cloudy

In [ ]:
# Creating Object of OneHotEncoder() class
encoder = OneHotEncoder()

In [ ]:
encoder

OneHotEncoder()

In [ ]:
encoder.fit_transform(df[['weather']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [ ]:
encoded = encoder.fit_transform(df[['weather']])

In [ ]:
encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (6, 3)>

In [ ]:
encoded.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
pd.DataFrame(encoded.toarray() , columns = encoder.get_feature_names_out())

   weather_cloudy  weather_rainy  weather_sunny
0             0.0            0.0            1.0
1             1.0            0.0            0.0
2             0.0            1.0            0.0
3             0.0            0.0            1.0
4             1.0            0.0            0.0
5             0.0            1.0            0.0

The `get_feature_names_out()` function is a method of the `OneHotEncoder` object. After you have fitted the `OneHotEncoder` to your data (e.g., using `encoder.fit(data)` or `encoder.fit_transform(data)`), this method allows you to retrieve the names of the new columns that the encoder generates. Each of these new column names will correspond to one of the unique categories from your original categorical feature. For example, if your original column was 'weather' with categories 'sunny', 'cloudy', and 'rainy', `get_feature_names_out()` would return an array like `['weather_cloudy', 'weather_rainy', 'weather_sunny']`.

In [ ]:
encoded_df = pd.DataFrame(encoded.toarray() , columns = encoder.get_feature_names_out())

In [ ]:
pd.concat([df , encoded_df] , axis = 1)

  weather  weather_cloudy  weather_rainy  weather_sunny
0   sunny             0.0            0.0            1.0
1  cloudy             1.0            0.0            0.0
2   rainy             0.0            1.0            0.0
3   sunny             0.0            0.0            1.0
4  cloudy             1.0            0.0            0.0
5   rainy             0.0            1.0            0.0

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'Color':['Red','Blue','Green','Red']
})

In [ ]:
# Method 1: Pandas
pd.get_dummies(df['Color'])

    Blue  Green    Red
0  False  False   True
1   True  False  False
2  False   True  False
3  False  False   True

In [ ]:
# Method 2: Scikit-Learn

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

encoded = encoder.fit_transform(
    df[['Color']]
)

In [ ]:
encoded.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**4. Dummy Encoding**


**Dummy Encoding** is a categorical encoding technique used to convert categorical variables into numerical format by creating binary (0 or 1) columns for categories while dropping one category as a reference (baseline) category.

It is very similar to **One-Hot Encoding**, but instead of creating a column for every category, Dummy Encoding creates **N−1 columns** for a feature with N categories.

The dropped category becomes the **reference category**, and its information can be inferred from the remaining columns.

Dummy Encoding is widely used in:

* Linear Regression
* Logistic Regression
* Statistical Modeling
* Econometrics
* Business Analytics



**Why Dummy Encoding is Needed**

Suppose we have:

| Color |
| ----- |
| Red   |
| Blue  |
| Green |

Using One-Hot Encoding:

| Red | Blue | Green |
| --- | ---- | ----- |
| 1   | 0    | 0     |
| 0   | 1    | 0     |
| 0   | 0    | 1     |

Three columns are created.

However, one column is redundant because if:

```text
Red = 0
Blue = 0
```

then the category must be:

```text
Green
```

Therefore, one column can be removed.



**Dummy Encoding**

Drop one category (Green).

Result:

| Red | Blue |
| --- | ---- |
| 1   | 0    |
| 0   | 1    |
| 0   | 0    |

Interpretation:

```text
Red=0 and Blue=0
⇒ Green
```

We reduced:

```text
3 Columns
↓
2 Columns
```

without losing information.

---

**Real-Life Analogy**

Suppose a company has three departments:

* HR
* IT
* Finance

Instead of asking:

```text
Is HR?
Is IT?
Is Finance?
```

You can ask only:

```text
Is HR?
Is IT?
```

If both answers are:

```text
No
No
```

Then automatically:

```text
Finance
```
This is exactly how Dummy Encoding works.

---

**Why Drop One Category?**

This is done to avoid the **Dummy Variable Trap**.


**Dummy Variable Trap**

One of the most asked interview questions.

Suppose:

| Red | Blue | Green |
| --- | ---- | ----- |
| 1   | 0    | 0     |
| 0   | 1    | 0     |
| 0   | 0    | 1     |

Notice:

[
Red + Blue + Green = 1
]

always.

This means one column can be perfectly predicted from the others.

Example:

[
Green = 1 - Red - Blue
]

This creates perfect multicollinearity.

---

**Problem**

Linear models become unstable.

Examples:

* Linear Regression
* Logistic Regression

Coefficient estimation becomes difficult.

---

### Solution

Drop one category.

Dummy Encoding removes this issue.

---

**5. Interpretation of Dummy Variables**

Suppose:

| Red | Blue |
| --- | ---- |
| 1   | 0    |
| 0   | 1    |
| 0   | 0    |

Interpretation:

**Row 1**

```text
Red = 1
Blue = 0
```

Category:

```text
Red
```

---

**Row 2**

```text
Red = 0
Blue = 1
```

Category:

```text
Blue
```

---

**Row 3**

```text
Red = 0
Blue = 0
```

Category:

```text
Green (Reference Category)
```

---
**Example 1: Customer Gender**

Original:

| Gender |
| ------ |
| Male   |
| Female |

Dummy Encoding:

| Male |
| ---- |
| 1    |
| 0    |

Interpretation:

```text
Male = 0
⇒ Female
```

---

**Example 2: Education**

Original:

```text
High School
Bachelor
Master
PhD
```

Dummy Encoding:

```text
Bachelor
Master
PhD
```

High School becomes baseline.

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Create a DataFrame for demonstration
dummy_data = pd.DataFrame({
    'City': ['Delhi', 'Mumbai', 'Chennai', 'Delhi', 'Mumbai', 'Chennai']
})

print("Original Data:")
display(dummy_data)

# Initialize OneHotEncoder with drop='first' for dummy encoding
# handle_unknown='ignore' ensures that if an unseen category appears during transform,
# it will be ignored rather than raising an error.
# sparse_output=False ensures the output is a dense NumPy array instead of a sparse matrix.
encoder = OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

# Fit and transform the 'City' column
encoded_features = encoder.fit_transform(dummy_data[['City']])

# Get feature names for the new columns
feature_names = encoder.get_feature_names_out(['City'])

# Create a DataFrame from the encoded features
encoded_df_dummy = pd.DataFrame(encoded_features, columns=feature_names)

# Concatenate the original and encoded data for comparison
dummy_encoded_comparison_df = pd.concat([dummy_data, encoded_df_dummy], axis=1)

print("\nDummy Encoded Data (Scikit-Learn):")
display(dummy_encoded_comparison_df)

Original Data:

      City
0    Delhi
1   Mumbai
2  Chennai
3    Delhi
4   Mumbai
5  Chennai

Dummy Encoded Data (Scikit-Learn):

      City  City_Delhi  City_Mumbai
0    Delhi         1.0          0.0
1   Mumbai         0.0          1.0
2  Chennai         0.0          0.0
3    Delhi         1.0          0.0
4   Mumbai         0.0          1.0
5  Chennai         0.0          0.0

In [ ]:
# Using Pandas

import pandas as pd

df = pd.DataFrame({
    'Color':['Red','Blue','Green','Red']
})

In [ ]:
pd.get_dummies(
    df['Color'],
    drop_first=True
)

   Green    Red
0  False   True
1  False  False
2   True  False
3  False   True

In [ ]:
pd.get_dummies(
    df['Color'],
    drop_first=True,
    dtype=int
)

   Green  Red
0      0    1
1      0    0
2      1    0
3      0    1

Blue becomes the reference category.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    drop='first'
)

X = encoder.fit_transform(
    df[['Color']]
)

**5. Frequency Encoding**

**Frequency Encoding** is a categorical encoding technique where each category is replaced by its frequency (or occurrence count percentage) in the dataset.

Instead of creating multiple columns like One-Hot Encoding, Frequency Encoding converts each category into a single numerical value representing how often that category appears.

This technique is particularly useful when dealing with **high-cardinality features**, meaning columns with many unique categories such as:

* City
* Product Category
* Occupation
* Customer Segment
* Device Type

It helps reduce dimensionality while preserving some information about category importance.

---

**Why Frequency Encoding is Needed**

Suppose we have:

| City   |
| ------ |
| Delhi  |
| Mumbai |
| Delhi  |
| Pune   |
| Delhi  |
| Mumbai |

Using One-Hot Encoding:

| Delhi | Mumbai | Pune |
| ----- | ------ | ---- |
| 1     | 0      | 0    |
| 0     | 1      | 0    |
| 1     | 0      | 0    |

More categories → More columns.

For 1000 cities:

```text
1000 new columns
```

This increases:

* Memory usage
* Training time
* Computational cost

Frequency Encoding solves this by creating only one column.

---

**How Frequency Encoding Works**

**Original Data**

| City   |
| ------ |
| Delhi  |
| Mumbai |
| Delhi  |
| Pune   |
| Delhi  |
| Mumbai |

---

**Step 1: Count Frequencies**

| City   | Frequency |
| ------ | --------- |
| Delhi  | 3         |
| Mumbai | 2         |
| Pune   | 1         |

---

**Step 2: Replace Categories**

| City |
| ---- |
| 3    |
| 2    |
| 3    |
| 1    |
| 3    |
| 2    |

Now the model sees numbers instead of text.

---

**3. Frequency vs Relative Frequency**

Two approaches exist.

**Count Frequency Encoding**

Uses raw counts.

| City   | Count |
| ------ | ----- |
| Delhi  | 3     |
| Mumbai | 2     |
| Pune   | 1     |

---

**Percentage Frequency Encoding**

Uses percentages.

Formula:

`[Frequency = \frac{Count}{Total\ Records}]`

---

Example:

Total Records = 6

Delhi:
```
[
frac{3}/{6}
]

[
= 0.5
]
```
---

Result:

| City   | Frequency |
| ------ | --------- |
| Delhi  | 0.50      |
| Mumbai | 0.33      |
| Pune   | 0.17      |

---

 **Real-Life Example**

**E-Commerce**

Feature:

| Product Category |
| ---------------- |
| Electronics      |
| Fashion          |
| Electronics      |
| Grocery          |

Frequency:

| Category    | Frequency |
| ----------- | --------- |
| Electronics | 2         |
| Fashion     | 1         |
| Grocery     | 1         |

Models may learn that highly frequent categories behave differently from rare categories.

---

**Banking Example**

Feature:

```text
Occupation
```

Values:

```text
Engineer
Doctor
Businessman
Student
```

Instead of creating many One-Hot columns:

Use Frequency Encoding.

Useful for:

* Loan Approval
* Credit Risk
* Customer Segmentation

---

**Advantages of Frequency Encoding**

**Handles High Cardinality**

Example:

```text
1000 Cities
```

One-Hot Encoding:

```text
1000 Columns
```

Frequency Encoding:

```text
1 Column
```

---

**Reduces Memory Usage**

Much more efficient.

---

**Faster Training**

Smaller feature space.

---

**Simple Implementation**

Only requires counting categories.

---

**Useful for Tree-Based Models**

Works well with:
* Random Forest
* XGBoost
* LightGBM
* CatBoost

---

**Disadvantages of Frequency Encoding**

**Information Loss**

Suppose:

| City   |
| ------ |
| Delhi  |
| Mumbai |

Frequency:

```text
Delhi = 100
Mumbai = 100
```

Both become:

```text
100
```

Model cannot distinguish them anymore.

Important category information is lost.

---

**Artificial Relationships**

Model may assume:

```text
Delhi = 100
Pune = 20
```

Delhi is "greater" than Pune.

This relationship may not exist.

---

**Rare Categories**

Rare categories receive very small values.

Sometimes meaningful information gets diluted.

In [ ]:
# Method 1: Count Frequency

import pandas as pd

df = pd.DataFrame({
    'City':['Delhi','Mumbai',
            'Delhi','Pune',
            'Delhi','Mumbai']
})

freq_map = df['City'].value_counts()

df['City_FE'] = df['City'].map(freq_map)

print("You observed that the 'City_FE' output is not unique. This is expected behavior for Frequency Encoding.")
print("Each occurrence of a city is replaced by its total frequency in the dataset.")
print("For example, 'Delhi' appears 3 times, so every 'Delhi' entry in 'City_FE' is 3.")
print("If multiple *different* cities happened to have the same frequency, they would also share the same encoded value.")
print("This encoding captures the prevalence of each category, not a unique identifier per row.")

display(df)

You observed that the 'City_FE' output is not unique. This is expected behavior for Frequency Encoding.
Each occurrence of a city is replaced by its total frequency in the dataset.
For example, 'Delhi' appears 3 times, so every 'Delhi' entry in 'City_FE' is 3.
If multiple *different* cities happened to have the same frequency, they would also share the same encoded value.
This encoding captures the prevalence of each category, not a unique identifier per row.

     City  City_FE
0   Delhi        3
1  Mumbai        2
2   Delhi        3
3    Pune        1
4   Delhi        3
5  Mumbai        2

### Method 2: Percentage Frequency Encoding

In [ ]:
# Calculate percentage frequency
percentage_freq_map = df['City'].value_counts(normalize=True)

df['City_PFE'] = df['City'].map(percentage_freq_map)

print("DataFrame with Percentage Frequency Encoded 'City':")
display(df)

DataFrame with Percentage Frequency Encoded 'City':

     City  City_FE  City_PFE
0   Delhi        3  0.500000
1  Mumbai        2  0.333333
2   Delhi        3  0.500000
3    Pune        1  0.166667
4   Delhi        3  0.500000
5  Mumbai        2  0.333333

**6. Count Encoding**

**Count Encoding** is a categorical encoding technique in which each category is replaced by the **number of times it appears in the dataset**.

Instead of creating multiple columns like One-Hot Encoding or assigning arbitrary numbers like Label Encoding, Count Encoding replaces each category with its occurrence count.

It is especially useful when dealing with **high-cardinality categorical features** (features having many unique categories).

---

**Why Count Encoding is Needed**

Suppose we have a feature:

| City   |
| ------ |
| Delhi  |
| Mumbai |
| Delhi  |
| Pune   |
| Delhi  |
| Mumbai |

Using One-Hot Encoding:

```text
Delhi   Mumbai   Pune
1         0       0
0         1       0
1         0       0
0         0       1
...
```

More categories → More columns.

If there are:

```text
10,000 Cities
```

One-Hot Encoding creates:

```text
10,000 Columns
```

This becomes expensive.

Count Encoding solves this by keeping only **one column**.

---

**How Count Encoding Works**

### Original Data

| City   |
| ------ |
| Delhi  |
| Mumbai |
| Delhi  |
| Pune   |
| Delhi  |
| Mumbai |

---

**Count Calculation**

| City   | Count |
| ------ | ----- |
| Delhi  | 3     |
| Mumbai | 2     |
| Pune   | 1     |

---

**Encoded Data**

| City |
| ---- |
| 3    |
| 2    |
| 3    |
| 1    |
| 3    |
| 2    |

---

The model now sees frequency information instead of category names.

---


**Advantages**

**Memory Efficient**

Only one column created.

---

**Handles High Cardinality**

Works well when categories are large.

Example:

```text
User_ID
Product_ID
Zip_Code
```

---

**Fast Computation**

Simple mapping operation.

---

**Useful for Tree-Based Models**

Works well with:

* Decision Trees
* Random Forest
* XGBoost
* LightGBM

---

**Disadvantages**

**Different Categories Can Have Same Count**

Example:

| City   | Count |
| ------ | ----- |
| Delhi  | 10    |
| Mumbai | 10    |

Both become:

```text
10
```

Information is partially lost.

---

**May Not Capture Category Meaning**

Only frequency is stored.

Actual category identity is removed.

---

**Sensitive to Data Changes*8

New data may change counts.

Requires recalculation.

---

**Data Leakage**

Wrong:

Compute counts on full dataset before train-test split.

Correct:

Compute counts using training data only.

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'City':['Delhi','Mumbai',
            'Delhi','Pune',
            'Delhi','Mumbai']
})

count_map = df['City'].value_counts()

df['City_Count'] = df['City'].map(count_map)

print(df)

     City  City_Count
0   Delhi           3
1  Mumbai           2
2   Delhi           3
3    Pune           1
4   Delhi           3
5  Mumbai           2

### Hands-on Example: Count Encoding Customer IDs

Let's consider a scenario where we have customer transaction data with a `CustomerID` column. If `CustomerID` were treated as a categorical feature, Count Encoding could help us understand the frequency of each customer's transactions without increasing dimensionality significantly. This is especially useful in datasets with many unique customer IDs.

We'll create a sample DataFrame and apply Count Encoding to the `CustomerID` column.

In [ ]:
import pandas as pd

# Create a sample DataFrame with CustomerID and some transaction data
customer_data = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108],
    'CustomerID': ['C1001', 'C1002', 'C1001', 'C1003', 'C1002', 'C1001', 'C1004', 'C1003'],
    'Amount': [50, 120, 75, 200, 90, 60, 300, 150]
})

print("Original Customer Data:")
display(customer_data)

# Calculate the frequency of each CustomerID
customer_id_counts = customer_data['CustomerID'].value_counts()

# Apply Count Encoding to the CustomerID column
customer_data['CustomerID_Encoded'] = customer_data['CustomerID'].map(customer_id_counts)

print("\nCustomer Data with Count Encoded CustomerID:")
display(customer_data)

Original Customer Data:

   TransactionID CustomerID  Amount
0            101      C1001      50
1            102      C1002     120
2            103      C1001      75
3            104      C1003     200
4            105      C1002      90
5            106      C1001      60
6            107      C1004     300
7            108      C1003     150

Customer Data with Count Encoded CustomerID:

   TransactionID CustomerID  Amount  CustomerID_Encoded
0            101      C1001      50                   3
1            102      C1002     120                   2
2            103      C1001      75                   3
3            104      C1003     200                   2
4            105      C1002      90                   2
5            106      C1001      60                   3
6            107      C1004     300                   1
7            108      C1003     150                   2

**7. Binary Encoding**

**Binary Encoding** is a categorical encoding technique that converts categories into numerical values and then represents those numerical values in binary format (0s and 1s).

It is considered a hybrid approach that combines:

* Label Encoding
* Binary Number Representation

Binary Encoding is mainly used when a categorical feature has **high cardinality** (many unique categories) and One-Hot Encoding would create too many columns.

It helps reduce dimensionality while still preserving category information.

---

**Why Do We Need Binary Encoding?**

Suppose we have a City column:

| City    |
| ------- |
| Delhi   |
| Mumbai  |
| Pune    |
| Chennai |
| Kolkata |

**One-Hot Encoding**

Creates:

| Delhi | Mumbai | Pune | Chennai | Kolkata |
| ----- | ------ | ---- | ------- | ------- |
| 1     | 0      | 0    | 0       | 0       |

For 100 cities:

```text
100 cities → 100 columns
```

This increases:

* Memory usage
* Training time
* Storage requirements

Binary Encoding reduces the number of columns significantly.

---

**How Binary Encoding Works**

The process happens in 3 steps.

**Step 1: Label Encode Categories**

Original Data:

| City    |
| ------- |
| Delhi   |
| Mumbai  |
| Pune    |
| Chennai |

Assign integers:

| City    | Label |
| ------- | ----- |
| Delhi   | 1     |
| Mumbai  | 2     |
| Pune    | 3     |
| Chennai | 4     |

---

**Step 2: Convert Labels to Binary**

| Label | Binary |
| ----- | ------ |
| 1     | 001    |
| 2     | 010    |
| 3     | 011    |
| 4     | 100    |

---

**Step 3: Split Binary Digits into Columns**

Final Output:

| B1 | B2 | B3 |
| -- | -- | -- |
| 0  | 0  | 1  |
| 0  | 1  | 0  |
| 0  | 1  | 1  |
| 1  | 0  | 0  |

Instead of 4 columns (One-Hot), we only need 3 columns.

---

**Complete Example**

**Original Data**

| City    |
| ------- |
| Delhi   |
| Mumbai  |
| Pune    |
| Chennai |
| Kolkata |
| Jaipur  |

---

**Label Encoding**

| City    | Label |
| ------- | ----- |
| Delhi   | 1     |
| Mumbai  | 2     |
| Pune    | 3     |
| Chennai | 4     |
| Kolkata | 5     |
| Jaipur  | 6     |

---

**Binary Representation**

| Label | Binary |
| ----- | ------ |
| 1     | 001    |
| 2     | 010    |
| 3     | 011    |
| 4     | 100    |
| 5     | 101    |
| 6     | 110    |

---

**Final Binary Encoded Data**

| B1 | B2 | B3 |
| -- | -- | -- |
| 0  | 0  | 1  |
| 0  | 1  | 0  |
| 0  | 1  | 1  |
| 1  | 0  | 0  |
| 1  | 0  | 1  |
| 1  | 1  | 0  |

---

**Why Binary Encoding is Efficient**

Suppose:

```text
100 Categories
```

**One-Hot Encoding**

Creates:

```text
100 Columns
```

**Binary Encoding**

Needs only:

[
\log_2(100)
]

≈

```text
7 Columns
```

Huge memory savings.

---


**Real-Life Examples**

**Example 1: Banking**

Feature:

```text
Occupation
```

Possible values:

```text
Doctor
Engineer
Teacher
Lawyer
Pilot
...
```

Hundreds of occupations.

One-Hot Encoding becomes large.

Binary Encoding works efficiently.

---

**Example 2: E-Commerce**

Feature:

```text
Product Category
```

Thousands of categories.

Binary Encoding reduces memory usage.

---

**Example 3: Insurance**

Feature:

```text
Vehicle Model
```

Thousands of unique vehicle models.

Binary Encoding is a practical choice.

---

**Enterprise-Level Usage**

Used when:

* Categories are too many for One-Hot Encoding.
* Need memory-efficient encoding.
* Tree-based models are being used.
* Data pipelines must scale efficiently.

Common in:

* Banking
* Insurance
* E-Commerce
* Fraud Detection
* Customer Analytics

---

**Advantages of Binary Encoding**

**1. Reduces Dimensionality**

Far fewer columns than One-Hot Encoding.

---

**2. Memory Efficient**

Consumes less RAM.

---

**3. Faster Training**

Smaller datasets train faster.

---

**4. Handles High Cardinality**

Suitable for hundreds or thousands of categories.

---

**5. Less Sparse Data**

One-Hot Encoding creates many zeros.

Binary Encoding produces denser features.

---

**Disadvantages of Binary Encoding**

**1. Less Interpretable**

Columns:

```text
B1
B2
B3
```

have no direct business meaning.

---

**2. Artificial Relationships**

Categories may appear numerically related because of binary patterns.

Example:

```text
Delhi = 001
Mumbai = 010
Pune = 011
```

These patterns don't represent real business relationships.

---

**3. Not Ideal for Linear Models**

Sometimes One-Hot Encoding performs better with:

* Linear Regression
* Logistic Regression

---


**When Should You Use Binary Encoding?**

**Recommended**

✅ 20–1000+ unique categories

✅ High-cardinality features

✅ Memory constraints

✅ Large datasets

---

**Avoid**

❌ Very small number of categories

❌ When interpretability is important

❌ When One-Hot Encoding is already manageable

In [ ]:
pip install category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.12/dist-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

In [ ]:
import pandas as pd
import category_encoders as ce

df = pd.DataFrame({
    'City':['Delhi','Mumbai','Pune',
            'Chennai','Kolkata']
})

encoder = ce.BinaryEncoder(cols=['City'])

encoded = encoder.fit_transform(df)

print(encoded)

   City_0  City_1  City_2
0       0       0       1
1       0       1       0
2       0       1       1
3       1       0       0
4       1       0       1

### Hands-on Example: Binary Encoding Product Categories

Let's apply Binary Encoding to a `Product Category` feature. Imagine an e-commerce dataset with various product categories. One-Hot Encoding might create too many columns if there are hundreds of categories. Binary Encoding offers a more compact representation.

We will create a sample DataFrame for product sales and encode the `Category` column.

In [ ]:
import pandas as pd
import category_encoders as ce

# Create a sample DataFrame with product categories
product_data = pd.DataFrame({
    'ProductID': [1, 2, 3, 4, 5, 6, 7, 8],
    'Category': ['Electronics', 'Apparel', 'Books', 'Electronics', 'Home Goods', 'Apparel', 'Books', 'Electronics'],
    'Sales': [150, 80, 45, 200, 120, 90, 60, 180]
})

print("Original Product Data:")
display(product_data)

# Initialize BinaryEncoder for the 'Category' column
binary_encoder = ce.BinaryEncoder(cols=['Category'])

# Fit and transform the 'Category' column
encoded_product_categories = binary_encoder.fit_transform(product_data['Category'])

# Concatenate the original DataFrame with the new encoded columns
product_data_encoded = pd.concat([product_data.drop('Category', axis=1), encoded_product_categories], axis=1)

print("\nProduct Data with Binary Encoded Category:")
display(product_data_encoded)

Original Product Data:

   ProductID     Category  Sales
0          1  Electronics    150
1          2      Apparel     80
2          3        Books     45
3          4  Electronics    200
4          5   Home Goods    120
5          6      Apparel     90
6          7        Books     60
7          8  Electronics    180

Product Data with Binary Encoded Category:

   ProductID  Sales  Category_0  Category_1  Category_2
0          1    150           0           0           1
1          2     80           0           1           0
2          3     45           0           1           1
3          4    200           0           0           1
4          5    120           1           0           0
5          6     90           0           1           0
6          7     60           0           1           1
7          8    180           0           0           1

**8. Hash Encoding (Hashing Trick)**

**Hash Encoding** is a categorical encoding technique that converts categories into numerical representations using a **hash function** instead of maintaining a mapping dictionary.

It is primarily used when a categorical feature contains **very large numbers of unique values (High Cardinality)**.

Examples:

```text
User_ID
Product_ID
Search_Query
URL
Device_ID
Transaction_ID
```

If we use One-Hot Encoding on these features:

```text
1,000,000 Unique Categories
```

we would create:

```text
1,000,000 Columns
```

which is impractical.

Hash Encoding solves this problem by mapping categories into a fixed number of columns using mathematical hashing.

---

**Why Hash Encoding is Needed**

Suppose we have:

| City    |
| ------- |
| Delhi   |
| Mumbai  |
| Pune    |
| Chennai |
| Kolkata |

With One-Hot Encoding:

| Delhi | Mumbai | Pune | Chennai | Kolkata |
| ----- | ------ | ---- | ------- | ------- |
| 1     | 0      | 0    | 0       | 0       |

For 5 cities, this is fine.

But imagine:

```text
500,000 Product IDs
```

One-Hot Encoding would create:

```text
500,000 Columns
```

Huge memory consumption.

Training becomes slow.

Hash Encoding keeps the number of columns fixed.

---

**What is a Hash Function?**

A **hash function** converts input data into a numerical value.

Example:

```text
Delhi
```

↓

```text
12578
```

```text
Mumbai
```

↓

```text
89342
```

The exact values don't matter.

What matters is that the same input always produces the same output.

---

**How Hash Encoding Works**

Suppose we decide:

```text
Number of Hash Buckets = 8
```

Categories:

```text
Delhi
Mumbai
Pune
Chennai
```

Hash Function Output:

| Category | Hash Value |
| -------- | ---------- |
| Delhi    | 3          |
| Mumbai   | 5          |
| Pune     | 2          |
| Chennai  | 7          |

Encoded Representation:

| H1 | H2 | H3 | H4 | H5 | H6 | H7 | H8 |
| -- | -- | -- | -- | -- | -- | -- | -- |
| 0  | 0  | 1  | 0  | 0  | 0  | 0  | 0  |

Only fixed columns are created.

Whether you have:

```text
100 Categories
```

or

```text
10 Million Categories
```

the output columns remain fixed.

---

**Real-Life Analogy**

Imagine a large apartment building.

Instead of remembering the exact apartment number of every resident:

```text
Rijul → Floor 3
Rahul → Floor 5
Aman → Floor 2
```

You place people into a fixed number of floors using a rule.

Many people may end up on the same floor.

This is exactly how Hash Encoding works.

---

**Hash Collision (Most Important Concept)**

The biggest drawback of Hash Encoding.

Suppose:

```text
Delhi → Bucket 3
Mumbai → Bucket 3
```

Both categories map to the same bucket.

This is called a **Hash Collision**.

---

**Example**

Hash Buckets:

```text
Bucket 1
Bucket 2
Bucket 3
Bucket 4
```

Results:

```text
Delhi → Bucket 3
Mumbai → Bucket 3
```

The model cannot distinguish between them perfectly.

Information is partially lost.

---
**What is Hash Collision?**

> A Hash Collision occurs when multiple categories are mapped to the same hash bucket during hash encoding.

---

**Choosing Number of Hash Buckets**

Very important in production.

**Too Few Buckets**

Example:

```text
10000 Categories
4 Buckets
```

Many collisions.

Poor model performance.

---

**Too Many Buckets**

Example:

```text
10000 Categories
10000 Buckets
```

Almost like One-Hot Encoding.

Memory usage increases.

---

**Rule of Thumb**

Start with:

```text
16
32
64
128
256
```

and tune experimentally.

---

**Advantages of Hash Encoding**

**Memory Efficient**

Fixed number of columns.

---

**Fast**

No mapping dictionary needed.

---

**Handles New Categories Automatically**

Training:

```text
Delhi
Mumbai
```

Production:

```text
Hyderabad
```

Still works.

No errors.

---

**Suitable for Streaming Data**

Useful in real-time systems.

---

**Scalable**

Works with millions of categories.

---

**Disadvantages of Hash Encoding**

**Hash Collisions**

Information loss.

---

**Less Interpretable**

Cannot easily determine which category belongs to which bucket.

---

**Feature Importance Difficult**

Understanding model decisions becomes harder.

---

**Not Reversible**

Unlike Label Encoding.

Cannot recover original category.

---

**When Should You Use Hash Encoding**

**Recommended**

✅ Product IDs

✅ User IDs

✅ Search Queries

✅ URLs

✅ Device IDs

✅ Clickstream Data

✅ Ad-Tech Systems

✅ Large Recommendation Systems

---

**Not Recommended**

❌ Gender

❌ Country

❌ Payment Type

❌ Education Level

❌ Small Category Features

Use One-Hot or Ordinal Encoding instead.

In [ ]:
from category_encoders import HashingEncoder

encoder = HashingEncoder(n_components=8)

encoded = encoder.fit_transform(df['City'])

### Hands-on Example: Hash Encoding Website URLs

Imagine a large web analytics dataset where you have a `Visited_URL` column with potentially millions of unique URLs. One-Hot Encoding this feature would be infeasible due to the massive number of resulting columns. Hash Encoding is an excellent choice here to reduce dimensionality while still capturing information about the URLs.

We'll create a sample DataFrame with `Visited_URL` and `PageViews` and then apply Hash Encoding to the URLs.

In [ ]:
import pandas as pd
from category_encoders import HashingEncoder

# Create a sample DataFrame with website URLs
web_data = pd.DataFrame({
    'SessionID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Visited_URL': [
        'www.example.com/home',
        'www.example.com/products/electronics',
        'www.example.com/about',
        'www.example.com/products/clothing',
        'www.example.com/home',
        'www.example.com/contact',
        'www.example.com/products/electronics',
        'www.example.com/blog/latest',
        'www.example.com/products/clothing',
        'www.example.com/services'
    ],
    'PageViews': [5, 12, 3, 8, 6, 2, 15, 4, 10, 7]
})

print("Original Web Data:")
display(web_data)

# Initialize HashingEncoder with a reasonable number of components (hash buckets)
# We'll use 8 buckets for demonstration, but for real-world scenarios with millions of URLs,
# you might choose a larger number like 256, 512, or 1024.

hashing_encoder = HashingEncoder(n_components=8, cols=['Visited_URL'])

# Fit and transform the 'Visited_URL' column
encoded_urls = hashing_encoder.fit_transform(web_data[['Visited_URL']])

# Concatenate the original DataFrame (without the original URL column) with the encoded columns
web_data_encoded = pd.concat([web_data.drop('Visited_URL', axis=1), encoded_urls], axis=1)

print("\nWeb Data with Hash Encoded URLs (using 8 buckets):")
display(web_data_encoded)

Original Web Data:

   SessionID                           Visited_URL  PageViews
0          1                  www.example.com/home          5
1          2  www.example.com/products/electronics         12
2          3                 www.example.com/about          3
3          4     www.example.com/products/clothing          8
4          5                  www.example.com/home          6
5          6               www.example.com/contact          2
6          7  www.example.com/products/electronics         15
7          8           www.example.com/blog/latest          4
8          9     www.example.com/products/clothing         10
9         10              www.example.com/services          7

Web Data with Hash Encoded URLs (using 8 buckets):

,SessionID,PageViews,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7
0,1,5,0,0,0,0,0,0,1,0
1,2,12,0,0,0,1,0,0,0,0
2,3,3,1,0,0,0,0,0,0,0
3,4,8,0,0,1,0,0,0,0,0
4,5,6,0,0,0,0,0,0,1,0
5,6,2,0,0,1,0,0,0,0,0
6,7,15,0,0,0,1,0,0,0,0
7,8,4,0,0,0,1,0,0,0,0
8,9,10,0,0,1,0,0,0,0,0
9,10,7,0,0,0,0,0,1,0,0

**9. Target Encoding (Mean Encoding)**

**Target Encoding** is a categorical encoding technique in which each category is replaced with a statistic derived from the **target variable**, most commonly the **mean of the target** for that category.

Unlike One-Hot Encoding, which creates multiple columns, Target Encoding converts each category into a single numerical value based on how that category relates to the target.

It is especially useful when dealing with **high-cardinality categorical features** (features with many unique categories).

---

**Why Target Encoding is Needed**

Suppose we have:

| City   | Loan_Default |
| ------ | ------------ |
| Delhi  | 1            |
| Delhi  | 0            |
| Mumbai | 0            |
| Mumbai | 0            |
| Pune   | 1            |

Target:

```text id="s1i9aa"
Loan_Default
```

Where:

```text id="z29ezf"
1 = Default
0 = No Default
```

---

### Calculate Mean Target

Delhi:
```
[(1+0)/2 = 0.5]
```
Mumbai:
```
[(0+0)/2 = 0]
```
Pune:
```
[1/1 = 1]
```
---

**Encoded Data**

| City   | Encoded Value |
| ------ | ------------- |
| Delhi  | 0.5           |
| Mumbai | 0             |
| Pune   | 1             |

Now the model can learn that:

```text id="qwx6e8"
Pune → Highest Default Risk
Delhi → Medium Risk
Mumbai → Lowest Risk
```

---

**Intuition Behind Target Encoding**

Instead of asking:

```text id="wz0z8o"
Which city is this?
```

Target Encoding asks:

```text id="trxsg5"
Historically, what happens for customers from this city?
```

This often provides much more useful information.

---

**Example**

| Product Category | Purchased |
| ---------------- | --------- |
| Electronics      | 1         |
| Electronics      | 1         |
| Electronics      | 0         |

Encoding:
```
[(1+1+0)/3]
```
```
[=0.67]
```
Electronics becomes:

```text id="46s65c"
0.67
```

---

**Step-by-Step Example**

**Original Dataset**

| City   | Purchased |
| ------ | --------- |
| Delhi  | 1         |
| Delhi  | 0         |
| Mumbai | 0         |
| Pune   | 1         |
| Pune   | 1         |

---

**Calculate Means**

Delhi:
```
[0.5]
```
Mumbai:
```
[0]
```
Pune:
```
[1]
```

---

**Replace Categories**

| City |
| ---- |
| 0.5  |
| 0.5  |
| 0    |
| 1    |
| 1    |

Simple and powerful.

---

**Why Target Encoding Works So Well**

Consider:

```text id="dx1v77"
Customer_ID
```

with:

```text id="w87fsy"
50,000 unique values
```

Using One-Hot Encoding:

```text id="t6z3wa"
50,000 columns
```

Huge memory usage.

Target Encoding:

```text id="4u9w4w"
1 column
```

Much smaller and often more predictive.

---

**Real-Life Examples**

**Banking**

Feature:

```text id="5fy39d"
Occupation
```

Target:

```text id="z1rf36"
Loan Default
```

Encoding:

| Occupation | Default Rate |
| ---------- | ------------ |
| Student    | 0.25         |
| Engineer   | 0.08         |
| Doctor     | 0.03         |

Model immediately learns risk levels.

---

**E-Commerce**

Feature:

```text id="zqzmk4"
Product Category
```

Target:

```text id="80gg4m"
Purchase
```

Categories become:

```text id="mp7uc5"
Purchase Probability
```

---

**Insurance**

Feature:

```text id="1b2j1q"
Vehicle Type
```

Target:

```text id="z26r06"
Claim Filed
```

Each vehicle type gets a claim probability score.

---

**Marketing**

Feature:

```text id="w7xuz0"
Campaign Source
```

Target:

```text id="ntc0xk"
Conversion
```

Campaigns become conversion-rate features.

---

**Advantages of Target Encoding**

**Handles High Cardinality**

Works well with:

```text id="3evlbe"
City
Product_ID
Merchant_ID
Occupation
```

---

**Reduces Dimensionality**

One column instead of thousands.

---

**Often Improves Accuracy**

Captures direct relationship with target.

---

**Memory Efficient**

Smaller feature space.

---

**Tree-Based Models Love It**

Works particularly well with:

* Random Forest
* XGBoost
* LightGBM
* CatBoost

---

**Biggest Problem: Data Leakage**

This is the most important interview topic.

Suppose:

| City  | Purchased |
| ----- | --------- |
| Delhi | 1         |
| Delhi | 0         |

Encoding:

```text id="9cgsc4"
Delhi = 0.5
```

The target variable was used to create the feature.

If not done carefully:

```text id="0px9k2"
Future information leaks into training.
```

Model appears extremely accurate.

But fails in production.

---

**Example of Leakage**

Wrong:

```python
encoder.fit_transform(
    X_full,
    y_full
)
```

before train-test split.

---

Correct:

```python
X_train
X_test

encoder.fit(
    X_train,
    y_train
)

encoder.transform(X_test)
```

In [ ]:
import pandas as pd

# Create a sample DataFrame with 'City' and a binary target 'Purchased'
df = pd.DataFrame({
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai'],
    'Purchased': [1, 0, 0, 1, 1, 0]
})

print("Original DataFrame:")
display(df)

# Calculate the mean of the target variable ('Purchased') for each 'City'
city_mean = df.groupby('City')['Purchased'].mean()

print("\nMean 'Purchased' for each City:")
print(city_mean)

# Map the mean 'Purchased' value back to the 'City' column
df['City_Encoded'] = df['City'].map(city_mean)

print("\nDataFrame after Target Encoding 'City':")
display(df)

Original DataFrame:

     City  Purchased
0   Delhi          1
1  Mumbai          0
2   Delhi          0
3    Pune          1
4   Delhi          1
5  Mumbai          0

Mean 'Purchased' for each City:
City
Delhi     0.666667
Mumbai    0.000000
Pune      1.000000
Name: Purchased, dtype: float64

DataFrame after Target Encoding 'City':

     City  Purchased  City_Encoded
0   Delhi          1      0.666667
1  Mumbai          0      0.000000
2   Delhi          0      0.666667
3    Pune          1      1.000000
4   Delhi          1      0.666667
5  Mumbai          0      0.000000

In [64]:
# Using Category Encoders
import pandas as pd
from category_encoders import TargetEncoder

# Create a sample DataFrame with 'City' and a binary target 'Purchased'
df = pd.DataFrame({
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Delhi', 'Mumbai'],
    'Purchased': [1, 0, 0, 1, 1, 0]
})

print("Original DataFrame:")
display(df)

encoder = TargetEncoder()

# Apply Target Encoding
df['City_Encoded'] = encoder.fit_transform(
    df['City'],
    df['Purchased']
)

print("\nDataFrame after Target Encoding 'City':")
display(df)

Original DataFrame:

     City  Purchased
0   Delhi          1
1  Mumbai          0
2   Delhi          0
3    Pune          1
4   Delhi          1
5  Mumbai          0

DataFrame after Target Encoding 'City':

     City  Purchased  City_Encoded
0   Delhi          1      0.525744
1  Mumbai          0      0.429074
2   Delhi          0      0.525744
3    Pune          1      0.565054
4   Delhi          1      0.525744
5  Mumbai          0      0.429074